---
title: "R_프로젝트 <언어권별 외국 관광객 4대궁 방문 추이>"
author: "최윤석"
date: '2022-04-08'
output:
  html_document: default
  pdf_document: default
---

## *<**서울 방문 외국인 관광객 수 대비 궁 방문 외국인 관람객 분석**>*

# https://data.seoul.go.kr/dataList/400/S/2/datasetView.do

# https://data.seoul.go.kr/dataList/10944/S/2/datasetView.do

# https://www.index.go.kr/potal/main/EachDtlPageDetail.do?idx_cd=1674


### *데이터 전처리 및 수정, 결합*
```{r}
library(RJDBC)
library(DBI)
library(rJava)
library(odbc)
library(dplyr)

# db 연결----
ins.drivers <- odbcListDrivers()

jdbc_D <-JDBC(driverClass = "oracle.jdbc.OracleDriver", 
              classPath = "C:/Database/dbhomeXE/jdbc/lib/ojdbc8.jar")

jdbc_D

dm_con1 <- dbConnect(jdbc_D, "jdbc:oracle:thin:@10.10.15.49:1521:XE","HR","HR")
dm_con1



# 엑셀파일 가져오기 (사용자 정의 함수 사용) ----
excel <- function(a, data){
  
  library(readxl)
  data <- read_excel(a)
  data <- rename(data, day = 일자)
  data <- rename(data, gyeongbok_adfee = 경복궁_유료)
  data <- rename(data, gyeongbok_free = 경복궁_무료)
  data <- rename(data, gyeongbok_total = 경복궁_일별_총원)
  data <- rename(data, gyeongbok_local = 경복궁_내국인)
  data <- rename(data, gyeongbok_eng = 경복궁_영어권)
  data <- rename(data, gyeongbok_jap = 경복궁_일본어권)
  data <- rename(data, gyeongbok_chi = 경복궁_중국어권)
  data <- rename(data, gyeongbok_oth = 경복궁_기타)
  data <- rename(data, gyeongbok_foreign_total = 경복궁_외국인_총원)
  
  data <- rename(data, deoksu_adfee = 덕수궁_유료)
  data <- rename(data, deoksu_free = 덕수궁_무료)
  data <- rename(data, deoksu_total = 덕수궁_일별_총원)
  data <- rename(data, deoksu_local = 덕수궁_내국인)
  data <- rename(data, deoksu_eng = 덕수궁_영어권)
  data <- rename(data, deoksu_jap = 덕수궁_일본어권)
  data <- rename(data, deoksu_chi = 덕수궁_중국어권)
  data <- rename(data, deoksu_oth = 덕수궁_기타)
  data <- rename(data, deoksu_foreign_total = 덕수궁_외국인_총원)
  
  data <- rename(data, changgyeong_adfee = 창경궁_유료)
  data <- rename(data, changgyeong_free = 창경궁_무료)
  data <- rename(data, changgyeong_total = 창경궁_일별_총원)
  data <- rename(data, changgyeong_local = 창경궁_내국인)
  data <- rename(data, changgyeong_eng = 창경궁_영어권)
  data <- rename(data, changgyeong_jap = 창경궁_일본어권)
  data <- rename(data, changgyeong_chi = 창경궁_중국어권)
  data <- rename(data, changgyeong_oth = 창경궁_기타)
  data <- rename(data, changgyeong_foreign_total = 창경궁_외국인_총원)
  
  data <- rename(data, changdeok_adfee = 창덕궁_유료)
  data <- rename(data, changdeok_free = 창덕궁_무료)
  data <- rename(data, changdeok_total = 창덕궁_일별_총원)
  data <- rename(data, changdeok_local = 창덕궁_내국인)
  data <- rename(data, changdeok_eng = 창덕궁_영어권)
  data <- rename(data, changdeok_jap = 창덕궁_일본어권)
  data <- rename(data, changdeok_chi = 창덕궁_중국어권)
  data <- rename(data, changdeok_oth = 창덕궁_기타)
  data <- rename(data, changdeok_foreign_total = 창덕궁_외국인_총원)
  
  return(data)
}

pal_2015 <- excel("C:/PR/R_Works/DIMA_Kita/4대궁 관람객 수 현황_2015.xlsx")
pal_2016 <- excel("C:/PR/R_Works/DIMA_Kita/4대궁 관람객 수 현황_2016.xlsx")
pal_2017 <- excel("C:/PR/R_Works/DIMA_Kita/4대궁 관람객 수 현황_2017.xlsx")
pal_2018 <- excel("C:/PR/R_Works/DIMA_Kita/4대궁 관람객 수 현황_2018.xlsx")
pal_2019 <- excel("C:/PR/R_Works/DIMA_Kita/4대궁 관람객 수 현황_2019.xlsx")
pal_2020 <- excel("C:/PR/R_Works/DIMA_Kita/4대궁 관람객 수 현황_2020.xlsx")



# 새로운 컬럼 생성 ----
pal_2015<- pal_2015 %>% mutate(total = gyeongbok_foreign_total+deoksu_foreign_total+
                                 changgyeong_foreign_total+changdeok_foreign_total)
pal_2016 <- pal_2016 %>% mutate(total = gyeongbok_foreign_total+deoksu_foreign_total+
                                  changgyeong_foreign_total+changdeok_foreign_total)
pal_2017 <- pal_2017 %>% mutate(total = gyeongbok_foreign_total+deoksu_foreign_total+
                                  changgyeong_foreign_total+changdeok_foreign_total)
pal_2018 <- pal_2018 %>% mutate(total = gyeongbok_foreign_total+deoksu_foreign_total+
                                  changgyeong_foreign_total+changdeok_foreign_total)
pal_2019 <- pal_2019 %>% mutate(total = gyeongbok_foreign_total+deoksu_foreign_total+
                                  changgyeong_foreign_total+changdeok_foreign_total)
pal_2020 <- pal_2020 %>% mutate(total = gyeongbok_foreign_total+deoksu_foreign_total+
                                  changgyeong_foreign_total+changdeok_foreign_total)



# db에 저장 ----
#dbWriteTable(dm_con1, "mini_project_15", pal_2015)
#dbWriteTable(dm_con1, "mini_project_16", pal_2016)
#dbWriteTable(dm_con1, "mini_project_17", pal_2017)
#dbWriteTable(dm_con1, "mini_project_18", pal_2018)
#dbWriteTable(dm_con1, "mini_project_19", pal_2019)
#dbWriteTable(dm_con1, "mini_project_20", pal_2020)



# db에서 필요한 부분만 가져오기 ----
db_15 <- "select * from mini_project_15 where day like '%년%'"
db_2015 <- dbGetQuery(dm_con1, db_15)


db_16 <- "select * from mini_project_16 where day like '%년%'"
db_2016 <- dbGetQuery(dm_con1, db_16)


db_17 <- "select * from mini_project_17 where day like '%년%'"
db_2017 <- dbGetQuery(dm_con1, db_17)


db_18 <- "select * from mini_project_18 where day like '%년%'"
db_2018 <- dbGetQuery(dm_con1, db_18)


db_19 <- "select * from mini_project_19 where day like '%년%'"
db_2019 <- dbGetQuery(dm_con1, db_19)


db_20 <- "select * from mini_project_20 where day like '%년%'"
db_2020 <- dbGetQuery(dm_con1, db_20)



# 컬럼명 소문자로 변경  ----


colnames(db_2015) <- tolower(colnames(db_2015))
colnames(db_2016) <- tolower(colnames(db_2016))
colnames(db_2017) <- tolower(colnames(db_2017))
colnames(db_2018) <- tolower(colnames(db_2018))
colnames(db_2019) <- tolower(colnames(db_2019))
colnames(db_2020) <- tolower(colnames(db_2020))
#View(db_2015)



# 데이터 결합 (bind-row) ---- 
pal_total <- bind_rows (db_2015, db_2016)
pal_total <- bind_rows (pal_total, db_2017)
pal_total <- bind_rows (pal_total, db_2018)
pal_total <- bind_rows (pal_total, db_2019)
pal_total <- bind_rows (pal_total, db_2020)
#View(pal_total)



# 새로운 컬럼 생성 (사용자 정의 함수) ----
eng_fun <- function(a){
  
  qfun <- a %>% mutate(eng_total = gyeongbok_eng+deoksu_eng+
                         changgyeong_eng+changdeok_eng)
  qfun <- qfun %>% select(day, eng_total)
  return(qfun)
}

jap_fun <- function(a){
  
  qfun <- a %>% mutate(jap_total = gyeongbok_jap+deoksu_jap+
                         changgyeong_jap+changdeok_jap)
  qfun <- qfun %>% select(day, jap_total)
  return(qfun)
}

chi_fun <- function(a){
  
  qfun <- a %>% mutate(chi_total = gyeongbok_chi+deoksu_chi+
                         changgyeong_chi+changdeok_chi)
  qfun <- qfun %>% select(day, chi_total)
  return(qfun)
}

oth_fun <- function(a){
  
  qfun <- a %>% mutate(oth_total = gyeongbok_oth+deoksu_oth+
                         changgyeong_oth+changdeok_oth)
  qfun <- qfun %>% select(day, oth_total)
  return(qfun)
}


pal_total_chi <- chi_fun(pal_total)
pal_total_jap <- jap_fun(pal_total)
pal_total_eng <- eng_fun(pal_total)
pal_total_oth <- oth_fun(pal_total)



# 데이터 결합 (full_join) ----
join_fun <- function(a, b, c, d){
  full_1 <- full_join(a, b, by="day")
  full_2 <- full_join(full_1, c, by="day")
  full_3 <- full_join(full_2, d, by="day")
  return(full_3)
}

pal_total_vis <- join_fun(pal_total_eng, pal_total_chi, pal_total_jap, pal_total_oth)
# View(pal_total_vis)



# 엑셀 파일 가져오기  
for_total <- read_excel("C:/PR/R_Works/DIMA_Kita/15-21 한국 방문 외국인.xlsx")



# 컬럼명 변경 후 데이터 결합 (left_join)
for_total <- rename(for_total, day = 일자)
vis_palvis <- left_join(pal_total, for_total, by="day")
#View(vis_palvis)
```


### *그래프 생성(막대그래프)*
####  **년도별 4대 궁 방문 외국인 총원 & 년도별 대한민국 방문 외국인 총원**
```{r}
library(ggplot2)
library(plotly)

options(scipen=100000)


# 그래프 생성
g1 <- ggplot(data = vis_palvis, aes(x=total, y=day))+
  geom_col(aes(fill=factor(day)),alpha=0.6, width=0.8)+
  theme_classic() + ggtitle("년도별 4대 궁 방문 외국인 총원") + xlim(0, 4000000)+
  geom_text(aes(label = total, vjust=0, hjust=-0.5), col="red")
ggplotly(g1)


g2 <- ggplot(data = vis_palvis, aes(x=총원, y=day))+
  geom_col(aes(fill=factor(day)),alpha=0.6, width=0.8)+
  theme_classic() + ggtitle("년도별 대한민국 방문 외국인 총원") + xlim(0, 18000000)+
  geom_text(aes(label = 총원, vjust=0, hjust=-0.1), col="red")
ggplotly(g2)
```


### *데이터 전처리 및  결합, 수정*
```{r}
library(stringr)
library(ggplot2)
library(dplyr)



# 데이터 결합 (full_join) 후 필요한 컬럼만 가져오기
vis_total_info <- full_join(pal_total_vis, vis_palvis, by="day")
#names(vis_total_info)
vis_total_info <- vis_total_info %>% select(1, 42, 2, 3, 4, 5, 43, 46, 49, 52, 55)
#View(vis_total_info)



# 한국 방문 대비 4대궁 방문 전체 외국인 비율
vis_total_info <- vis_total_info %>% mutate(vis_avg_total =(total/총원)*100)



# 한국방문 대비 4대궁 방문 / 미방문 영어권 비율
vis_total_info <- vis_total_info %>% mutate(궁_방문객_영어권 = (eng_total/영어_총원)*100)  
vis_total_info <- vis_total_info %>% mutate(궁_미방문객_영어권 = (영어_총원 - eng_total)/영어_총원*100)


# 한국방문 대비 4대궁 방문 / 미방문 일본어권 비율
vis_total_info <- vis_total_info %>% mutate(궁_방문객_일본어권 = (jap_total/일본_총원)*100)  
vis_total_info <- vis_total_info %>% mutate(궁_미방문객_일본어권 = (일본_총원 - jap_total)/일본_총원*100)


# 한국방문 대비 4대궁 방문 / 미방문 중국어권 비율
vis_total_info <- vis_total_info %>% mutate(궁_방문객_중국어권 = (chi_total/중국_총원)*100)  
vis_total_info <- vis_total_info %>% mutate(궁_미방문객_중국어권 = (중국_총원 - chi_total)/중국_총원*100)


# 한국방문 대비 4대궁 방문 / 미방문 기타 비율
vis_total_info <- vis_total_info %>% mutate(궁_방문객_기타 = (oth_total/기타_총원)*100)  
vis_total_info <- vis_total_info %>% mutate(궁_미방문객_기타 = (기타_총원-oth_total)/기타_총원*100)


# vis_total_info %>% select(12, 13, 14, 15, 16)
# vis_total_info[,c(5,9)]
# names(vis_total_info)
# vis_total_info %>% select(12, 13, 14, 15, 16, 17)
# vis_total_info[,c(5,8)]
# View(vis_total_info)



# 엑셀파일 가져오기기
visit_info <- read_excel("C:/PR/R_Works/DIMA_Kita/mini_project.xlsx")
# View(visit_info)


# 필요 컬럼만 뽑아서 가져오기 (년도별/언어권 별 4대궁 방문 외국인 비율 (방문자 / 미방문자))
per_2015_eng <- visit_info[c(12:13),c(1,2)]
per_2015_jap <- visit_info[c(14:15),c(1,2)]
per_2015_chi <- visit_info[c(16:17),c(1,2)]
per_2015_oth <- visit_info[c(18:19),c(1,2)]


per_2016_eng <- visit_info[c(12:13),c(1,3)]
per_2016_jap <- visit_info[c(14:15),c(1,3)]
per_2016_chi <- visit_info[c(16:17),c(1,3)]
per_2016_oth <- visit_info[c(18:19),c(1,3)]


per_2017_eng <- visit_info[c(12:13),c(1,4)]
per_2017_jap <- visit_info[c(14:15),c(1,4)]
per_2017_chi <- visit_info[c(16:17),c(1,4)]
per_2017_oth <- visit_info[c(18:19),c(1,4)]


per_2018_eng <- visit_info[c(12:13),c(1,5)]
per_2018_jap <- visit_info[c(14:15),c(1,5)]
per_2018_chi <- visit_info[c(16:17),c(1,5)]
per_2018_oth <- visit_info[c(18:19),c(1,5)]


per_2019_eng <- visit_info[c(12:13),c(1,6)]
per_2019_jap <- visit_info[c(14:15),c(1,6)]
per_2019_chi <- visit_info[c(16:17),c(1,6)]
per_2019_oth <- visit_info[c(18:19),c(1,6)]


per_2020_eng <- visit_info[c(12:13),c(1,7)]
per_2020_jap <- visit_info[c(14:15),c(1,7)]
per_2020_chi <- visit_info[c(16:17),c(1,7)]
per_2020_oth <- visit_info[c(18:19),c(1,7)]

```


### *그래프 생성(파이그래프)*
####  **년도 및 언어권 별 4대궁 방문, 미방문자 비율**
```{r}
library(stringr)
library(ggplot2)
library(dplyr)

# 년도별 / 언어권별 4대궁 방문,미방문자 비율 파이 그래프
library(gridExtra)

# 2015년
p1_2015 <- ggplot(data=per_2015_eng)+geom_bar(aes(x="", y=`2015`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2015`/2 + c(0, cumsum(`2015`)[-length(`2015`)]),
                label = paste0(round(`2015`/ sum(`2015`)*100,1), "%")))+
  ggtitle("2015년 한국 방문 대비 4대궁 방문 비율 (영어권)")

p2_2015 <- ggplot(data=per_2015_jap)+geom_bar(aes(x="", y=`2015`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2015`/2 + c(0, cumsum(`2015`)[-length(`2015`)]),
                label = paste0(round(`2015`/ sum(`2015`)*100,1), "%")))+
  ggtitle("2015년 한국 방문 대비 4대궁 방문 비율 (일본어권)")

p3_2015 <- ggplot(data=per_2015_chi)+geom_bar(aes(x="", y=`2015`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2015`/2 + c(0, cumsum(`2015`)[-length(`2015`)]),
                label = paste0(round(`2015`/ sum(`2015`)*100,1), "%")))+
  ggtitle("2015년 한국 방문 대비 4대궁 방문 비율 (중국어권)")

p4_2015 <- ggplot(data=per_2015_oth)+geom_bar(aes(x="", y=`2015`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2015`/2 + c(0, cumsum(`2015`)[-length(`2015`)]),
                label = paste0(round(`2015`/ sum(`2015`)*100,1), "%")))+
  ggtitle("2015년 한국 방문 대비 4대궁 방문 비율 (기타)")

grid.arrange(p1_2015, p2_2015, p3_2015, p4_2015, ncol=2, nrow=2)



# 2016년
p1_2016 <- ggplot(data=per_2016_eng)+geom_bar(aes(x="", y=`2016`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2016`/2 + c(0, cumsum(`2016`)[-length(`2016`)]),
                label = paste0(round(`2016`/ sum(`2016`)*100,1), "%")))+
  ggtitle("2016년 한국 방문 대비 4대궁 방문 비율 (영어권)")

p2_2016 <- ggplot(data=per_2016_jap)+geom_bar(aes(x="", y=`2016`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2016`/2 + c(0, cumsum(`2016`)[-length(`2016`)]),
                label = paste0(round(`2016`/ sum(`2016`)*100,1), "%")))+
  ggtitle("2016년 한국 방문 대비 4대궁 방문 비율 (일본어권)")

p3_2016 <- ggplot(data=per_2016_chi)+geom_bar(aes(x="", y=`2016`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2016`/2 + c(0, cumsum(`2016`)[-length(`2016`)]),
                label = paste0(round(`2016`/ sum(`2016`)*100,1), "%")))+
  ggtitle("2016년 한국 방문 대비 4대궁 방문 비율 (중국어권)")

p4_2016 <- ggplot(data=per_2016_oth)+geom_bar(aes(x="", y=`2016`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2016`/2 + c(0, cumsum(`2016`)[-length(`2016`)]),
                label = paste0(round(`2016`/ sum(`2016`)*100,1), "%")))+
  ggtitle("2016년 한국 방문 대비 4대궁 방문 비율 (기타)")

grid.arrange(p1_2016, p2_2016, p3_2016, p4_2016, ncol=2, nrow=2)


# 2017년
p1_2017 <- ggplot(data=per_2017_eng)+geom_bar(aes(x="", y=`2017`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2017`/2 + c(0, cumsum(`2017`)[-length(`2017`)]),
                label = paste0(round(`2017`/ sum(`2017`)*100,1), "%")))+
  ggtitle("2017년 한국 방문 대비 4대궁 방문 비율 (영어권)")

p2_2017 <- ggplot(data=per_2017_jap)+geom_bar(aes(x="", y=`2017`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2017`/2 + c(0, cumsum(`2017`)[-length(`2017`)]),
                label = paste0(round(`2017`/ sum(`2017`)*100,1), "%")))+
  ggtitle("2017년 한국 방문 대비 4대궁 방문 비율 (일본어권)")

p3_2017 <- ggplot(data=per_2017_chi)+geom_bar(aes(x="", y=`2017`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2017`/2 + c(0, cumsum(`2017`)[-length(`2017`)]),
                label = paste0(round(`2017`/ sum(`2017`)*100,1), "%")))+
  ggtitle("2017년 한국 방문 대비 4대궁 방문 비율 (중국어권)")

p4_2017 <- ggplot(data=per_2017_oth)+geom_bar(aes(x="", y=`2017`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2017`/2 + c(0, cumsum(`2017`)[-length(`2017`)]),
                label = paste0(round(`2017`/ sum(`2017`)*100,1), "%")))+
  ggtitle("2017년 한국 방문 대비 4대궁 방문 비율 (기타)")

grid.arrange(p1_2017, p2_2017, p3_2017, p4_2017, ncol=2, nrow=2)


# 2018년
p1_2018 <- ggplot(data=per_2018_eng)+geom_bar(aes(x="", y=`2018`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2018`/2 + c(0, cumsum(`2018`)[-length(`2018`)]),
                label = paste0(round(`2018`/ sum(`2018`)*100,1), "%")))+
  ggtitle("2018년 한국 방문 대비 4대궁 방문 비율 (영어권)")

p2_2018 <- ggplot(data=per_2018_jap)+geom_bar(aes(x="", y=`2018`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2018`/2 + c(0, cumsum(`2018`)[-length(`2018`)]),
                label = paste0(round(`2018`/ sum(`2018`)*100,1), "%")))+
  ggtitle("2018년 한국 방문 대비 4대궁 방문 비율 (일본어권)")

p3_2018 <- ggplot(data=per_2018_chi)+geom_bar(aes(x="", y=`2018`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2018`/2 + c(0, cumsum(`2018`)[-length(`2018`)]),
                label = paste0(round(`2018`/ sum(`2018`)*100,1), "%")))+
  ggtitle("2018년 한국 방문 대비 4대궁 방문 비율 (중국어권)")

p4_2018 <- ggplot(data=per_2018_oth)+geom_bar(aes(x="", y=`2018`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2018`/2 + c(0, cumsum(`2018`)[-length(`2018`)]),
                label = paste0(round(`2018`/ sum(`2018`)*100,1), "%")))+
  ggtitle("2018년 한국 방문 대비 4대궁 방문 비율 (기타)")

grid.arrange(p1_2018, p2_2018, p3_2018, p4_2018, ncol=2, nrow=2)


# 2019년
p1_2019 <- ggplot(data=per_2019_eng)+geom_bar(aes(x="", y=`2019`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2019`/2 + c(0, cumsum(`2019`)[-length(`2019`)]),
                label = paste0(round(`2019`/ sum(`2019`)*100,1), "%")))+
  ggtitle("2019년 한국 방문 대비 4대궁 방문 비율 (영어권)")

p2_2019 <- ggplot(data=per_2019_jap)+geom_bar(aes(x="", y=`2019`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2019`/2 + c(0, cumsum(`2019`)[-length(`2019`)]),
                label = paste0(round(`2019`/ sum(`2019`)*100,1), "%")))+
  ggtitle("2019년 한국 방문 대비 4대궁 방문 비율 (일본어권)")

p3_2019 <- ggplot(data=per_2019_chi)+geom_bar(aes(x="", y=`2019`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2019`/2 + c(0, cumsum(`2019`)[-length(`2019`)]),
                label = paste0(round(`2019`/ sum(`2019`)*100,1), "%")))+
  ggtitle("2019년 한국 방문 대비 4대궁 방문 비율 (중국어권)")

p4_2019 <- ggplot(data=per_2019_oth)+geom_bar(aes(x="", y=`2019`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2019`/2 + c(0, cumsum(`2019`)[-length(`2019`)]),
                label = paste0(round(`2019`/ sum(`2019`)*100,1), "%")))+
  ggtitle("2019년 한국 방문 대비 4대궁 방문 비율 (기타)")

grid.arrange(p1_2019, p2_2019, p3_2019, p4_2019, ncol=2, nrow=2)


# 2020년
p1_2020 <- ggplot(data=per_2020_eng)+geom_bar(aes(x="", y=`2020`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2020`/2 + c(0, cumsum(`2020`)[-length(`2020`)]),
                label = paste0(round(`2020`/ sum(`2020`)*100,1), "%")))+
  ggtitle("2020년 한국 방문 대비 4대궁 방문 비율 (영어권)")

p2_2020 <- ggplot(data=per_2020_jap)+geom_bar(aes(x="", y=`2020`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2020`/2 + c(0, cumsum(`2020`)[-length(`2020`)]),
                label = paste0(round(`2020`/ sum(`2020`)*100,1), "%")))+
  ggtitle("2020년 한국 방문 대비 4대궁 방문 비율 (일본어권)")

p3_2020 <- ggplot(data=per_2020_chi)+geom_bar(aes(x="", y=`2020`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2020`/2 + c(0, cumsum(`2020`)[-length(`2020`)]),
                label = paste0(round(`2020`/ sum(`2020`)*100,1), "%")))+
  ggtitle("2020년 한국 방문 대비 4대궁 방문 비율 (중국어권)")

p4_2020 <- ggplot(data=per_2020_oth)+geom_bar(aes(x="", y=`2020`, fill=방문여부), width=1, stat = "identity")+
  coord_polar("y", start = 0)+
  geom_text(aes(x="", y= `2020`/2 + c(0, cumsum(`2020`)[-length(`2020`)]),
                label = paste0(round(`2020`/ sum(`2020`)*100,1), "%")))+
  ggtitle("2020년 한국 방문 대비 4대궁 방문 비율 (기타)")

grid.arrange(p1_2020, p2_2020, p3_2020, p4_2020, ncol=2, nrow=2)
```

### *데이터 전처리 및 결합, 수정*
```{r}
library(ggiraphExtra)
library(mapproj)
library(maps)
library(ggplot2)
library(tibble)
# map_data("state")



# 엑셀 파일 가져오기 (사용자 정의 함수) ----
xl_usa <- function(x){
  
  switch(x, us_1 = read_excel("C:/PR/R_Works/DIMA_Kita/my_USA.xlsx", sheet = 1, col_names = T),
         us_2 = read_excel("C:/PR/R_Works/DIMA_Kita/my_USA.xlsx", sheet = 2, col_names = T),
         us_3 = read_excel("C:/PR/R_Works/DIMA_Kita/my_USA.xlsx", sheet = 3, col_names = T),
         us_4 = read_excel("C:/PR/R_Works/DIMA_Kita/my_USA.xlsx", sheet = 4, col_names = T),
         us_5 = read_excel("C:/PR/R_Works/DIMA_Kita/my_USA.xlsx", sheet = 5, col_names = T),
         us_6 = read_excel("C:/PR/R_Works/DIMA_Kita/my_USA.xlsx", sheet = 6, col_names = T),
         us_7 = read_excel("C:/PR/R_Works/DIMA_Kita/my_USA.xlsx", sheet = 7, col_names = T))
         
}

us_1 <- xl_usa("us_1")
us_2 <- xl_usa("us_2")
us_3 <- xl_usa("us_3")
us_4 <- xl_usa("us_4")
us_5 <- xl_usa("us_5")
us_6 <- xl_usa("us_6")
us_7 <- xl_usa("us_7")



# 데이터 결합 후 NA 값 0으로 변경 (사용자 정의 함수)  ----
bind_fun <- function(a, b, c, d, e, f, g){
  aa <- bind_rows(a, b)
  aaa <- bind_rows(aa, c)
  aaaa <- bind_rows(aaa, d)
  aaaaa <- bind_rows(aaaa, e)
  aaaaaa <- bind_rows(aaaaa, f)
  aaaaaaa <- bind_rows(aaaaaa, g)
  xxx <- aaaaaaa %>% mutate(search_rate, replace(., is.na(.), 0))
  xxx <- xxx %>% arrange(-search_rate, state)
  return(xxx)
}

my_data <- bind_fun(us_1, us_2, us_3, us_4, us_5, us_6, us_7)
# my_data
# View(my_data)



# db에 파일 저장 후 불러오기
# dbWriteTable(dm_con1, "mini_project_usmap", my_data)


USA_map <- "select * from mini_project_usmap order by search_rate desc, state"
USA_map <- dbGetQuery(dm_con1, USA_map)
# View(USA_map)
USA_map <- map_data("state")
```


### *그래프 생성(맵그래프)*
####  **2015년~2020년 미국 주(state)별 4대궁 관련 단어 검색률**
##### 관심도 수치 0~100 (100에 가까울수록 검색률 높음)
```{r}
# 맵 그래프
ggChoropleth(data=my_data, # 지도에 표현할 데이터
             map=USA_map,  # 지도데이터
             aes(fill=search_rate,
                 map_id=state),
             title="USA search Rate(Palace)",
             col="darkblue",
             interactive=T)
```

